### PR TITLE
Feature/muc admin

### PR DESCRIPTION
**Pull request by paulfariello**

### CODE REVIEW

**Comment by cdidier** [comment]
change "Add documentation" and "Add help" commit messages to be a little bit more explicit

**Comment by fschlich** [comment]
The ban and kick help pages have a file conflict with irssi (overwrite the irssi help page of the same name) and should probably be renamed, e.g. to xmppban and xmppkick: https://anonscm.debian.org/cgit/collab-maint/irssi-plugin-xmpp.git/commit/?id=b2a85761b447983f87f9c07f8ae38baecffd12e4

**Comment by ailin-nemui** [comment]
in the future maybe we/irssi should move to protocol specific help subdirectories like help/irc/ban etc

**Comment by cdidier** [comment]
Merged in https://github.com/cdidier/irssi-xmpp/pull/48.

**Pull request closed without merging**
