### PR TITLE
Fix registration on TLS-only servers

### PR DESCRIPTION
**Pull request by vaygr**
I'm amused how this feature is underrated :)

I couldn't find any lightweight client (read C) that'd have a basic registration feature. And this plugin was supposed to be my savior. Unfortunately I quickly found out it crashes when registration is performed.

When I fixed the crash, I discovered that loudmouth simply doesn't support in-band registration over TLS (which about 99% of servers force nowadays).

So this PR fixes 2 problems:

1. It checks for the error without relying on an error code, which many servers dropped support for, see [XEP-0086](https://xmpp.org/extensions/xep-0086.html).
2. It establishes TLS connection _before_ checking for and performing registration if it's available (which may come from stream features, see [XEP-0077](https://xmpp.org/extensions/xep-0077.html#streamfeature)).

I tested it on many servers, however I'm sure not all servers announce registration in stream features, so maybe it makes sense to force-send the register request.

Some code is borrowed from loudmouth itself.

### CODE REVIEW

**Review by cdidier — APPROVED** [review]

**Comment by cdidier** [comment]
Unfortunately it doesn't work as expected, so I had to revert this.
But using part of this, I've improved the error reporting when trying to register, see https://github.com/cdidier/irssi-xmpp/commit/81c426aaf21d1eddc9b591bbcfad4da8bda03ff5.

**Comment by vaygr** [comment]
@cdidier thanks, do you have any logs showing the problem? I'm sure I tested this at least on 3 different servers, and it worked well.

**Comment by cdidier** [comment]
Hi @vagyr, do you have some server addresses where registration doesn't work (and some that work too)? so I can test and see the issue by myself.

After looking at the original code, irssi-xmpp is setting the proper ssl or starttls configuration on the loudmouth connection (with the set_ssl function). From what I tested, the starttls connection was established before the registration.

With the merged code, the registration was stuck on the xmpp-sasl feature (if I remember correctly) after sending the message with the xmpp-tls xmlns.

**Comment by vaygr** [comment]
Yeah, one of them is `jabber.otr.im`.

**Pull request merged**
