### PR TITLE
oob uploads in muc

### PR DESCRIPTION
**Pull request by ailin-nemui**
otherwise I get a PM for every upload in a channel.

### CODE REVIEW

**Comment by myzinsky** [comment]
I have the same issue, every upload I get this notification in a PM ...

**Comment by ailin-nemui** [comment]
does my patch work for you?

**Comment by myzinsky** [comment]
Just checking ...

**Comment by myzinsky** [comment]
Yes, the patch works very well! Should be accepted IMHO, but I have not reviewed the code!

**Review by cdidier — APPROVED** [review]

**Pull request merged**
